// This file is automatically generated.

interface CssExports {
  'column-1': string;
  'column-10': string;
  'column-11': string;
  'column-12': string;
  'column-2': string;
  'column-3': string;
  'column-4': string;
  'column-5': string;
  'column-6': string;
  'column-7': string;
  'column-8': string;
  'column-9': string;
  'column1': string;
  'column10': string;
  'column11': string;
  'column12': string;
  'column2': string;
  'column3': string;
  'column4': string;
  'column5': string;
  'column6': string;
  'column7': string;
  'column8': string;
  'column9': string;
  'container': string;
  'form-row': string;
  'formRow': string;
  'section': string;
}

declare var cssExports: CssExports;
export = cssExports;
