// This file is automatically generated.

interface CssExports {
  'button': string;
  'container': string;
  'icon': string;
  'icon-content': string;
  'iconContent': string;
  'optical': string;
}

declare var cssExports: CssExports;
export = cssExports;
