// This file is automatically generated.

interface CssExports {
  'container': string;
  'form': string;
  'nav': string;
  'side': string;
}

declare var cssExports: CssExports;
export = cssExports;
