// This file is automatically generated.

interface CssExports {
  'account-section': string;
  'account-section__avatar': string;
  'accountSection': string;
  'accountSectionAvatar': string;
  'container': string;
  'dropdownItem': string;
  'dropdownMenu': string;
  'dropdown__item': string;
  'dropdown__menu': string;
  'footer': string;
  'header': string;
  'headerLogo': string;
  'headerMenu': string;
  'header__logo': string;
  'header__menu': string;
}

declare var cssExports: CssExports;
export = cssExports;
