// This file is automatically generated.

interface CssExports {
  'language': string;
  'nav': string;
  'nav-item': string;
  'nav-item__right': string;
  'navItem': string;
  'navItemRight': string;
  'search-icon': string;
  'searchIcon': string;
}

declare var cssExports: CssExports;
export = cssExports;
