// This file is automatically generated.

interface CssExports {
  'container': string;
  'dropdown': string;
  'dropdownItem': string;
  'dropdown__item': string;
  'user-avatar': string;
  'userAvatar': string;
}

declare var cssExports: CssExports;
export = cssExports;
