version: '3.3'

services:
  vendora-mysql:
    image: mysql
    container_name: vendora-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - /mysql:/var/lib/mysql
    networks:
      - vendora-networks

networks:
  vendora-networks:
    driver: bridge