// This file is automatically generated.

interface CssExports {
  'button': string;
  'buttonText': string;
  'button__text': string;
  'buttons': string;
  'container': string;
  'fields': string;
}

declare var cssExports: CssExports;
export = cssExports;
