// This file is automatically generated.

interface CssExports {
  'button': string;
  'button--success': string;
  'buttonIcon': string;
  'buttonSuccess': string;
  'buttonText': string;
  'button__icon': string;
  'button__text': string;
  'buttons': string;
  'container': string;
  'fields': string;
}

declare var cssExports: CssExports;
export = cssExports;
