// This file is automatically generated.

interface CssExports {
  'adjust-button': string;
  'adjustButton': string;
  'number-inputbox': string;
  'numberInputbox': string;
}

declare var cssExports: CssExports;
export = cssExports;
