// This file is automatically generated.

interface CssExports {
  'container': string;
  'form': string;
  'form-outter': string;
  'formOutter': string;
  'nav': string;
  'nav-buton': string;
  'navButon': string;
  'next': string;
  'prev': string;
  'section-container': string;
  'sectionContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
