// This file is automatically generated.

interface CssExports {
  'container': string;
  'main-section': string;
  'mainSection': string;
  'question-container': string;
  'question-group-container': string;
  'questionContainer': string;
  'questionGroupContainer': string;
  'step-bar': string;
  'step-bar-container': string;
  'stepBar': string;
  'stepBarContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
