// This file is automatically generated.

interface CssExports {
  'container': string;
  'main-section': string;
  'mainSection': string;
  'question-container': string;
  'question-group': string;
  'question-group-container': string;
  'questionContainer': string;
  'questionGroup': string;
  'questionGroupContainer': string;
  'step-bar-container': string;
  'stepBarContainer': string;
  'steps': string;
}

declare var cssExports: CssExports;
export = cssExports;
