// This file is automatically generated.

interface CssExports {
  'container': string;
  'decorator': string;
  'decorator-number': string;
  'decoratorNumber': string;
  'fields': string;
}

declare var cssExports: CssExports;
export = cssExports;
