// This file is automatically generated on.

export const container: string;
export const file: string;
export const fileMap: string;
export const mappings: string;
export const names: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;