// This file is automatically generated on.

export const antMenuItemSelected: string;
export const container: string;
export const containerContent: string;
export const dropdownItem: string;
export const dropdownMenu: string;
export const footer: string;
export const header: string;
export const logo: string;
export const menuItem: string;
export const menuItemButton: string;
export const profileIcon: string;