// This file is automatically generated.

interface CssExports {
  'container': string;
  'container-content': string;
  'containerContent': string;
  'logo': string;
}

declare var cssExports: CssExports;
export = cssExports;
