// This file is automatically generated.

interface CssExports {
  'gray-panel': string;
  'gray-panel__title': string;
  'gray-panel__title-lg': string;
  'grayPanel': string;
  'grayPanelTitle': string;
  'grayPanelTitleLg': string;
  'highlight': string;
  'openTime': string;
  'title-dot': string;
  'titleDot': string;
}

declare var cssExports: CssExports;
export = cssExports;
