// This file is automatically generated.

interface CssExports {
  'ant-menu-item-selected': string;
  'antMenuItemSelected': string;
  'container': string;
  'container-content': string;
  'containerContent': string;
  'dropdown-item': string;
  'dropdown-menu': string;
  'dropdownItem': string;
  'dropdownMenu': string;
  'footer': string;
  'header': string;
  'logo': string;
  'menuItem': string;
  'menuItem-button': string;
  'menuItemButton': string;
  'profileIcon': string;
}

declare var cssExports: CssExports;
export = cssExports;
