// This file is automatically generated.

interface CssExports {
  'container': string;
  'heading': string;
  'input': string;
  'title': string;
}

declare var cssExports: CssExports;
export = cssExports;
