// This file is automatically generated.

interface CssExports {
  'comment': string;
  'commentAuthor': string;
  'commentButtons': string;
  'commentIcon': string;
  'commentText': string;
  'comment__author': string;
  'comment__buttons': string;
  'comment__icon': string;
  'comment__text': string;
  'container': string;
}

declare var cssExports: CssExports;
export = cssExports;
