// This file is automatically generated.

interface CssExports {
  'container': string;
  'description': string;
  'highlight': string;
  'image': string;
  'index': string;
  'item': string;
  'section': string;
  'text': string;
  'textLeft': string;
  'textRight': string;
  'text__left': string;
  'text__right': string;
  'title': string;
  'title-dot': string;
  'titleDot': string;
}

declare var cssExports: CssExports;
export = cssExports;
