// This file is automatically generated.

interface CssExports {
  'lender-board': string;
  'lenderBoard': string;
  'main-section': string;
  'mainSection': string;
}

declare var cssExports: CssExports;
export = cssExports;
