// This file is automatically generated.

interface CssExports {
  'about-text': string;
  'aboutText': string;
  'aboutus': string;
  'info-card': string;
  'info-group': string;
  'info-image': string;
  'infoCard': string;
  'infoGroup': string;
  'infoImage': string;
  'infoText': string;
  'lender-board': string;
  'lenderBoard': string;
  'aboutus-section': string;
  'aboutus-section__h1': string;
  'aboutusSection': string;
  'aboutusSectionH1': string;
  'main-section': string;
  'main-section__button': string;
  'main-section__button-group': string;
  'mainSection': string;
  'mainSectionButton': string;
  'mainSectionButtonGroup': string;
  'number': string;
  'our-rate': string;
  'ourRate': string;
  'rate-figure': string;
  'rate-text': string;
  'rateFigure': string;
  'rateText': string;
  'section': string;
}

declare var cssExports: CssExports;
export = cssExports;
