// This file is automatically generated.

interface CssExports {
  'dropdown': string;
  'select': string;
  'selectItem': string;
  'select_item': string;
  'step-container': string;
  'stepContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
