// This file is automatically generated.

interface CssExports {
  'avatar': string;
  'container': string;
  'dropdown-item': string;
  'dropdownItem': string;
  'logo': string;
  'menu': string;
}

declare var cssExports: CssExports;
export = cssExports;
