// This file is automatically generated.

interface CssExports {
  'body': string;
  'footer': string;
  'header': string;
  'logo': string;
}

declare var cssExports: CssExports;
export = cssExports;
